### ISSUE TITLE
Course issue

### ISSUE THREAD

**Issue by coryhouse** [YoneMoreno/LearnReactRedux#1]
Hi Enoy - I am able to run your app without issue. I'd suggest installing the latest version of Node and trying again. 

Also, be sure to check this list: https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first

**Comment by coryhouse** [comment]
Also, are you able to run the final version of the course exercise? (under exercise files in final module folder)

**Comment by YoneMoreno** [comment]
Hello Cory House and thank you for your time and patience!

When I tried to execute your finalized project it gave me an error I suppose I need to change some paths or something:

C:\Users\YonePC\Downloads\react-redux-react-router-es6\15-production-builds\production-builds-exercise-files>npm start
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "star
t"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\YonePC\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\YonePC\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\YonePC\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\YonePC\Downloads\react-redux-react-router-es6\15-production-builds\production-builds-exercise-files
\npm-debug.log

About Nodejs I had version 6.11.3 installed and I have just installed version 6.11.4 but it shows as this:
![reduxerror](https://user-images.githubusercontent.com/22214901/31454458-673c0a76-aead-11e7-91a5-33bb2910ba5e.PNG)

Also checking you list:
1 After npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents
@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupporte
d platform for fsevents@1.1.2: wanted {"os":"darwin","ar
ch":"any"} (current: {"os":"win32","arch":"x64"})

2 Path doesn't include spaces right



4 Files with . are in the root yes


5 I am running with npm start

6 I have no problems with webpack I think.

7 I have not used ESlint with webstorm before, just it with sublime for the first course.

8 Indeed I did because it required privilege mode to state npm start

9 I used both OS and WS command lines

10 I have not reached this point yet.

11 I have just reinstalled Node.

I will prove to install node 5.12.0 ;)

I have the same problem with node 5 :=( Hopefully opening the web with Mozilla insted of Chrome gives me some aid:

(I need to upload the photo into another web cause Github just lets me upload the first into here)

https://imgur.com/N9y35Wq

"import declaration may only appear at top level of a module"

When I click on bundle.js we see the line which has the error:

https://imgur.com/0V0Brwa

import Reeact from 'react';

How could we fix this?

Thank you Cory for your time.

**Comment by coryhouse** [comment]
I bet number 10 on the list is your issue. Run this to check:

SET NODE_ENV

**Comment by YoneMoreno** [comment]
Thank you Cory House for helping me.

I wish you had reason but it says that NODE_ENV is not defined, how could I fix this?

![nodeenv2](https://user-images.githubusercontent.com/22214901/31485910-6d8aa254-af2d-11e7-8f7e-9114fdfce175.PNG)

**Comment by coryhouse** [comment]
Found the issue!  You're using the wrong import in two spots:

https://www.dropbox.com/s/iowhdh8ocg3hl8t/Screenshot%202017-10-12%2006.30.26.png?dl=0
https://www.dropbox.com/s/tc98n8482nloitt/Screenshot%202017-10-12%2006.30.47.png?dl=0

Why did you use that different import?

**Comment by YoneMoreno** [comment]
Helllo Cory House and thank you for being so helpful and take time for this issue!

Hopefully I did what you said and fixed the imports:
https://imgur.com/vGVSdkX
https://imgur.com/0GbbMJX

However both on Chrome and Firefox:
https://imgur.com/P7PjcZO
If you click on the bundle.js to see where the error is:
https://imgur.com/lhrGPyj
Which looks like there is an error in one import which looks like:

	import React from 'react';

All of the code chunck where is the error:

/***/ },
/* 740 */
/***/ function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(process) {var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
	
	function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }
	
	**import React from 'react';**
	import warning from './routerWarning';
	import { routerShape } from './PropTypes';
	
	var _React$PropTypes = React.PropTypes;
	var bool = _React$PropTypes.bool;
	var object = _React$PropTypes.object;
	var string = _React$PropTypes.string;
	var func = _React$PropTypes.func;
	var oneOfType = _React$PropTypes.oneOfType;
	
	
	function isLeftClickEvent(event) {
	  return event.button === 0;
	}
	
	function isModifiedEvent(event) {
	  return !!(event.metaKey || event.altKey || event.ctrlKey || event.shiftKey);
	}
	
	// TODO: De-duplicate against hasAnyProperties in createTransitionManager.
	function isEmptyObject(object) {
	  for (var p in object) {
	    if (Object.prototype.hasOwnProperty.call(object, p)) return false;
	  }return true;
	}
	
	function createLocationDescriptor(to, _ref) {
	  var query = _ref.query;
	  var hash = _ref.hash;
	  var state = _ref.state;
	
	  if (query || hash || state) {
	    return { pathname: to, query: query, hash: hash, state: state };
	  }
	
	  return to;
	}

Could you suggest me any improvement please?

Also I did to use the different import because of the IDE itself doesn't recognize the import which we have change to now:
https://imgur.com/4L2kH12

Says cannot resolve symbol 'Link'

Any help? Could you take a little bit more time to help me? Because I would like to be able to fix by myself but I do not have any clues to help myself in this error.

Thank you Cory House!

**Comment by coryhouse** [comment]
Look at the screenshots I sent again. Your React router related import doesn't match mine in this pic: https://imgur.com/0GbbMJX

**Comment by YoneMoreno** [comment]
Hello Thank you thank you Cory House for your time you are right I changed the import  path. Thank you because it worked here you have the proof:
![prove](https://user-images.githubusercontent.com/22214901/31545237-77b90a1a-b016-11e7-9a29-d21067ddda7d.PNG)

Thank you as the idiom says Two heads think betther than one I will be more careful with imports now ;)

**Comment by coryhouse** [comment]
Great to hear! 👍
